# Project information
site_name: Vossendijk Regels
site_url: 'https://regels.vossendijkrp.nl/'
site_description: 'Wet en regelgeving van Vossendijk RP'
site_author: 'Vossendijk'

# Copyright
copyright: Copyright &copy; 2022 Vossendijk

# Congiguration
theme:
  name: material
  features:
    # - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: img/logo.png
  logo: img/logo.png
  language: nl
plugins:
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: home.md
  - Algemeen Regels: algemeneregels.md
  - Crimineel Circuit: crimineel.md
  - Hulpdiensten: hulpdiensten.md
  - Content Regels: content.md
  - Value of Life: valueoflife.md
  - New Life Rule: newliferule.md
